/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AplikasiPerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPerhitunganHari
     */
    public AplikasiPerhitunganHari() {
        initComponents();
        
        setupEventListeners();
        
    }
   

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        lblTahunAwal = new javax.swing.JLabel();
        lblTahunAkhir = new javax.swing.JLabel();
        btnHitung = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        lblHariPertama = new javax.swing.JLabel();
        lblHariTerakhir = new javax.swing.JLabel();
        lblKabisat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jCalendar2 = new com.toedter.calendar.JCalendar();
        btnHitungSelisih = new javax.swing.JButton();
        lblSelisihHari = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitungan Hari");
        setResizable(false);

        lblTahunAwal.setText("Tahun Awal");

        lblTahunAkhir.setText("Tahun Akhir");

        btnHitung.setText("Hitung");

        lblHasil.setText("Hasil");

        lblHariPertama.setText("Hari Pertama");

        lblHariTerakhir.setText("Hari Terakhir");

        lblKabisat.setText("Kabisat");

        jLabel1.setText("APLIKASI PERHITUNGAN HARI");

        jCalendar1.setMaxSelectableDate(null);
        jCalendar1.setMinSelectableDate(null);
        jCalendar1.setTodayButtonText("Hari Ini");
        jCalendar1.setTodayButtonVisible(true);
        jCalendar1.setWeekOfYearVisible(false);

        jCalendar2.setDate(new java.util.Date(1761360987000L));
        jCalendar2.setMaxSelectableDate(null);
        jCalendar2.setMinSelectableDate(null);
        jCalendar2.setTodayButtonText("Hari Ini");
        jCalendar2.setTodayButtonVisible(true);
        jCalendar2.setWeekOfYearVisible(false);

        btnHitungSelisih.setText("Hitung Selisih");

        lblSelisihHari.setText("Selisih Hari");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(248, 248, 248))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(lblTahunAwal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTahunAkhir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(lblHariPertama, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(127, 127, 127)
                                .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHitungSelisih))
                            .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHariTerakhir, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKabisat, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSelisihHari, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 190, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(lblTahunAwal)
                    .addComponent(jCalendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTahunAkhir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(lblHasil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHariPertama)
                    .addComponent(btnHitung)
                    .addComponent(btnHitungSelisih))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHariTerakhir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblKabisat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblSelisihHari)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
   
    
    private void setupEventListeners() {
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
        
        btnHitungSelisih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungSelisihActionPerformed(evt);
            }
        });

        jCalendar1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
        public void propertyChange(java.beans.PropertyChangeEvent evt) {
            jCalendar1PropertyChange(evt);
            }
    });
        jCalendar2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
    public void propertyChange(java.beans.PropertyChangeEvent evt) {
        jCalendar2PropertyChange(evt);
    }
});
    }

        private void jCalendar1PropertyChange(java.beans.PropertyChangeEvent evt) {
            if ("calendar".equals(evt.getPropertyName())) {
            hitungInformasiBulanOtomatis();
        }
    }
        
        private void jCalendar2PropertyChange(java.beans.PropertyChangeEvent evt) {
            if ("calendar".equals(evt.getPropertyName())) {
            // Otomatis hitung selisih ketika jCalendar2 berubah
            hitungSelisihHari();
    }
}
        
        
     private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {                                         
         hitungInformasiBulan();
    }   
    
     private void hitungInformasiBulan() {
     try {
        // DEBUG: Cek apakah calendar berfungsi
        System.out.println("jCalendar1 date: " + jCalendar1.getDate());
        System.out.println("jCalendar2 date: " + jCalendar2.getDate());
        
        // Ambil tanggal dari JCalendar
        java.util.Calendar cal = jCalendar1.getCalendar();
        int tahun = cal.get(java.util.Calendar.YEAR);
        int bulan = cal.get(java.util.Calendar.MONTH) + 1;
        
        System.out.println("Tahun: " + tahun + ", Bulan: " + bulan);
        
        // ✅ TAMBAH KODE PERHITUNGAN INI:
        // Buat LocalDate untuk bulan dan tahun yang dipilih
        java.time.LocalDate tanggal = java.time.LocalDate.of(tahun, bulan, 1);
        
        // Hitung jumlah hari dalam bulan
        int jumlahHari = tanggal.lengthOfMonth();
        
        // Dapatkan hari pertama dan terakhir
        String hariPertama = tanggal.getDayOfWeek().getDisplayName(
            java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
        java.time.LocalDate tanggalTerakhir = tanggal.withDayOfMonth(jumlahHari);
        String hariTerakhir = tanggalTerakhir.getDayOfWeek().getDisplayName(
            java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
        
        // Cek tahun kabisat
        boolean isKabisat = tanggal.isLeapYear();
        String statusKabisat = isKabisat ? "Tahun Kabisat" : "Bukan Tahun Kabisat";

        // Update label hasil
        lblHasil.setText("Jumlah hari: " + jumlahHari);
        lblHariPertama.setText("Hari pertama: " + hariPertama);
        lblHariTerakhir.setText("Hari terakhir: " + hariTerakhir);
        lblKabisat.setText("Status tahun: " + statusKabisat);

    } catch (Exception ex) {
        ex.printStackTrace(); // Tampilkan error lengkap
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Terjadi kesalahan: " + ex.getMessage(), 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }


}
     
    private void btnHitungSelisihActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        hitungSelisihHari();
    }                                                

    private void hitungInformasiBulanOtomatis() {
        hitungInformasiBulan();
    }


    private void hitungSelisihHari() {
        try {
            // Ambil tanggal dari kedua JCalendar
            java.util.Calendar cal1 = jCalendar1.getCalendar();
            java.util.Calendar cal2 = jCalendar2.getCalendar();
        
            // Konversi ke LocalDate
            java.time.LocalDate tanggal1 = java.time.LocalDate.of(
                cal1.get(java.util.Calendar.YEAR),
                cal1.get(java.util.Calendar.MONTH) + 1,
                cal1.get(java.util.Calendar.DAY_OF_MONTH)
            );
        
            java.time.LocalDate tanggal2 = java.time.LocalDate.of(
                cal2.get(java.util.Calendar.YEAR),
                cal2.get(java.util.Calendar.MONTH) + 1,
                cal2.get(java.util.Calendar.DAY_OF_MONTH)
            );
        
            // Hitung selisih hari
            long selisihHari = java.time.temporal.ChronoUnit.DAYS.between(tanggal1, tanggal2);
        
            // Tampilkan hasil
            lblSelisihHari.setText("Selisih Hari: " + Math.abs(selisihHari) + " hari");
        
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Terjadi kesalahan saat menghitung selisih: " + ex.getMessage(), 
                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganHari().setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnHitungSelisih;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblHariPertama;
    private javax.swing.JLabel lblHariTerakhir;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblKabisat;
    private javax.swing.JLabel lblSelisihHari;
    private javax.swing.JLabel lblTahunAkhir;
    private javax.swing.JLabel lblTahunAwal;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
}
