/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class AplikasiPerhitunganHari extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPerhitunganHari
     */
    public AplikasiPerhitunganHari() {
        initComponents();
        setupEventListeners();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBulan = new javax.swing.JLabel();
        comboBulan = new javax.swing.JComboBox<>();
        lblTahun = new javax.swing.JLabel();
        spinnerTahun = new javax.swing.JSpinner();
        btnHitung = new javax.swing.JButton();
        lblHasil = new javax.swing.JLabel();
        lblHariPertama = new javax.swing.JLabel();
        lblHariTerakhir = new javax.swing.JLabel();
        lblKabisat = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblSelisihHari = new javax.swing.JLabel();
        lblTahunAwal = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        lblTahunAkhir = new javax.swing.JLabel();
        jCalendar2 = new com.toedter.calendar.JCalendar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Perhitungan Hari");
        setResizable(false);

        lblBulan.setText("Bulan awal");

        comboBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni ", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        lblTahun.setText("Tahun awal");

        spinnerTahun.setModel(new javax.swing.SpinnerNumberModel(2024, 1900, 2100, 1));
        spinnerTahun.setValue(spinnerTahun.getValue());

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        lblHasil.setText("Hasil");

        lblHariPertama.setText("Hari Pertama");

        lblHariTerakhir.setText("Hari Terakhir");

        lblKabisat.setText("Kabisat");

        jLabel1.setText("APLIKASI PERHITUNGAN HARI");

        lblSelisihHari.setText("Selisih Hari");

        lblTahunAwal.setText("Tanggal Awal");

        jCalendar1.setMaxSelectableDate(null);
        jCalendar1.setMinSelectableDate(null);
        jCalendar1.setTodayButtonText("Hari Ini");
        jCalendar1.setTodayButtonVisible(true);
        jCalendar1.setWeekOfYearVisible(false);

        lblTahunAkhir.setText("Tanggal Akhir");

        jCalendar2.setDate(new java.util.Date(1761360987000L));
        jCalendar2.setMaxSelectableDate(null);
        jCalendar2.setMinSelectableDate(null);
        jCalendar2.setTodayButtonText("Hari Ini");
        jCalendar2.setTodayButtonVisible(true);
        jCalendar2.setWeekOfYearVisible(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblSelisihHari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKabisat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHariTerakhir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHariPertama, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBulan)
                            .addComponent(lblTahun))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTahunAwal)
                            .addComponent(jCalendar1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTahunAkhir)
                            .addComponent(jCalendar2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBulan)
                    .addComponent(comboBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTahunAwal)
                    .addComponent(lblTahunAkhir))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTahun)
                            .addComponent(spinnerTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCalendar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(lblHasil)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblHariPertama)
                    .addComponent(btnHitung))
                .addGap(18, 18, 18)
                .addComponent(lblHariTerakhir)
                .addGap(18, 18, 18)
                .addComponent(lblKabisat)
                .addGap(18, 18, 18)
                .addComponent(lblSelisihHari)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
          try {
        // Ambil data dari combo box dan spinner
        int bulanIndex = comboBulan.getSelectedIndex() + 1;
        int tahun = (Integer) spinnerTahun.getValue();

        // Validasi input dari combo box dan spinner
        if (bulanIndex < 1 || bulanIndex > 12) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Pilih bulan yang valid!", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buat LocalDate dari combo box dan spinner
        java.time.LocalDate tanggalDariCombo = java.time.LocalDate.of(tahun, bulanIndex, 1);
        
        // Ambil tanggal dari JCalendar1
        java.util.Date selectedDate1 = jCalendar1.getDate();
        java.time.LocalDate tanggalDariCalendar1 = null;
        
        if (selectedDate1 != null) {
            // Konversi java.util.Date ke java.time.LocalDate
            tanggalDariCalendar1 = selectedDate1.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();
        }

        // Tentukan tanggal mana yang akan digunakan untuk perhitungan
        java.time.LocalDate tanggalUntukPerhitungan;
        
        if (tanggalDariCalendar1 != null) {
            // Jika JCalendar1 memiliki tanggal, gunakan itu
            tanggalUntukPerhitungan = tanggalDariCalendar1;
            
            // Sinkronisasi: Update combo box dan spinner agar sesuai dengan JCalendar1
            int bulanCalendar = tanggalDariCalendar1.getMonthValue();
            int tahunCalendar = tanggalDariCalendar1.getYear();
            
            comboBulan.setSelectedIndex(bulanCalendar - 1);
            spinnerTahun.setValue(tahunCalendar);
        } else {
            // Jika JCalendar1 kosong, gunakan input dari combo box dan spinner
            tanggalUntukPerhitungan = tanggalDariCombo;
            
            // Sinkronisasi: Update JCalendar1 agar sesuai dengan input combo box dan spinner
            java.util.Date date = java.sql.Date.valueOf(tanggalDariCombo);
            jCalendar1.setDate(date);
        }

        // Hitung jumlah hari dalam bulan
        int jumlahHari = tanggalUntukPerhitungan.lengthOfMonth();
        
        // Dapatkan hari pertama dan terakhir
        String hariPertama = tanggalUntukPerhitungan.getDayOfWeek().getDisplayName(
            java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
        
        java.time.LocalDate tanggalTerakhir = tanggalUntukPerhitungan.withDayOfMonth(jumlahHari);
        String hariTerakhir = tanggalTerakhir.getDayOfWeek().getDisplayName(
            java.time.format.TextStyle.FULL, new java.util.Locale("id", "ID"));
        
        // Cek tahun kabisat
        boolean isKabisat = tanggalUntukPerhitungan.isLeapYear();
        String statusKabisat = isKabisat ? "Tahun Kabisat" : "Bukan Tahun Kabisat";

        // Hitung selisih hari antara dua tanggal dari JCalendar
        long selisihHari = 0;
        java.util.Date selectedDate2 = jCalendar2.getDate();
        
        if (selectedDate1 != null && selectedDate2 != null) {
            java.time.LocalDate tanggalCalendar2 = selectedDate2.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();
            
            if (!tanggalCalendar2.isBefore(tanggalDariCalendar1)) {
                selisihHari = java.time.temporal.ChronoUnit.DAYS.between(tanggalDariCalendar1, tanggalCalendar2);
            }
        }

        // Update label hasil
        lblHasil.setText("Jumlah hari: " + jumlahHari);
        lblHariPertama.setText("Hari pertama: " + hariPertama);
        lblHariTerakhir.setText("Hari terakhir: " + hariTerakhir);
        lblKabisat.setText("Status tahun: " + statusKabisat);
        lblSelisihHari.setText("Selisih hari: " + selisihHari + " hari");

    } catch (Exception ex) {
        ex.printStackTrace(); // Untuk debugging
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Terjadi kesalahan: " + ex.getMessage(), 
            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnHitungActionPerformed
    
   
    
     private void setupEventListeners() {
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });
    }

     

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPerhitunganHari.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPerhitunganHari().setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHitung;
    private javax.swing.JComboBox<String> comboBulan;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBulan;
    private javax.swing.JLabel lblHariPertama;
    private javax.swing.JLabel lblHariTerakhir;
    private javax.swing.JLabel lblHasil;
    private javax.swing.JLabel lblKabisat;
    private javax.swing.JLabel lblSelisihHari;
    private javax.swing.JLabel lblTahun;
    private javax.swing.JLabel lblTahunAkhir;
    private javax.swing.JLabel lblTahunAwal;
    private javax.swing.JSpinner spinnerTahun;
    // End of variables declaration//GEN-END:variables
}
